title: Amelia Halabi
production_url: https://www.ameliahalabi.com

icons: '/assets/icons'
images: '/assets/images'

sass:
  sass_dir: '/assets/_sass'
  style: compressed

permalink: /blog/:title

paginate: 5
paginate_path: /blog/page:num/

plugins:
  - jekyll-paginate
