title: Amelia Halabi
production_url: https://www.ameliahalabi.com

icons: '/assets/icons'
images: '/assets/images'

sass:
  sass_dir: '/assets/_sass'
  style: compressed

permalink: /blog/:title.html

pagination:
  enabled: true
  per_page: 10
  sort_reverse: true

plugins:
  - jekyll-paginate-v2
